# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userbid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('won', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pimage', models.ImageField(upload_to='productimages')),
                ('description', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('finaldate', models.DateField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bidprice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(upload_to='userimages')),
                ('address', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='products',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.Categories'),
        ),
        migrations.AddField(
            model_name='biddetails',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.Products'),
        ),
        migrations.AddField(
            model_name='biddetails',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.UserProfile'),
        ),
    ]
